### ISSUE TITLE
LambdaDependency ContentUri Is not Updating

### ISSUE THREAD

**Issue by WoodProgrammer** [jenkinsci/aws-sam-plugin#12]
Hello,

I'm using AWS Sam Plugin version 1.2.2.

But in actually sam plugin do not update contentUri for Layer resource of cloudformation. 

You can check my cloudformation.yaml file shown as below;

```
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my-service
      ContentUri: ./dependencies
      CompatibleRuntimes:
        - python3.6
```

SAM plugin updating codeUri path to s3 uri but in actually I cannot see any update on Dependency resource ? How Can I fix that, which points are I'm missing ? 

Thanks
